main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:id>', views.profile_view, name="profile_view"),
    path('search/', views.search, name='search'),
    path('addroommate/', views.add_roommate, name='add_roommate'),
    path('addaddress/', views.add_address, name='add_address'),
    path('address/<int:pk>', views.address_view, name='address_view'),
    path('address-add-review/<int:pk>', views.address_add_review, name='address_add_review'),
    path('edit-profile', views.edit_profile, name="edit-profile"),
    path('roommate-add-review/<int:pk>', views.roommate_add_review, name='roommate_add_review'),
] 

ratemyroomie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf  import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from roommates.models import UserProfile, Address, Attribute
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
import json
# Create your views here.

def home(request):
    return render(request, 'main/index.html')


def profile(request):
    user = UserProfile.objects.get(user=request.user)
    attributes = Attribute.objects.filter(author=user)
    return render(request, 'main/roommatedetails.html', {'userp': user, 'attributes': attributes})


def profile_view(request, id):
    user = UserProfile.objects.get(id=id)
    all_attributes = Attribute.objects.all()
    attributes = Attribute.objects.filter(author=user)
    return render(request, 'main/roommatedetails.html', {'userp': user, 'attributes': attributes, 'all_attributes': all_attributes})


def search(request):
    roomate_key = request.GET.get('Roommate', None)
    address_key = request.GET.get('Address', None)
    if roomate_key:
        roommate = request.GET['Roommate']
        
        qs1 = UserProfile.objects.filter(user__username__icontains=roommate)
        qs2 = UserProfile.objects.filter(user__first_name__icontains=roommate)
        qs3 = UserProfile.objects.filter(user__last_name__icontains=roommate)
        qs4 = UserProfile.objects.filter(full_name__icontains=roommate)
        roommate_list = qs1 | qs2 | qs3 | qs4
        total = roommate_list.count()
        
        context = {
            'roommate_list': roommate_list,
            'total': total,
            'keyword': roommate,
            'key': 'Roommate',
            }
        return render(request, 'main/search.html', context)
    if address_key:
        address = request.GET['Address']
        qs1 = Address.objects.filter(name__icontains=address)
        qs2 = Address.objects.filter(location__icontains=address)
        address_list = qs1 | qs2
        total = address_list.count()
        
        context = {
            'address_list': address_list,
            'total': total,
            'keyword': address,
            'key': 'Address',
            }
        return render(request, 'main/searchaddress.html', context)
    return render(request, 'main/search.html')

def add_roommate(request):
    if request.method == "POST":
        full_name = request.POST['full-name']
        email = request.POST['email']
        phone = request.POST['phone']
        mobile = request.POST['mobile']
        address = request.POST['address']
        photo = request.FILES['picture__input']
        userprofile = UserProfile( full_name=full_name, email=email, phone=phone, mobile=mobile, address=address, photo=photo)
        userprofile.save()
        attributes = request.POST.get('attribute_list', None)
        if attributes:
            for i in json.loads(attributes):
                attr = userprofile.attribute_set.get_or_create(name=i[0], rating=i[1],)[0]
                attr.save()
        messages.success(request, 'Roommate added successfully')
        return render(request, 'main/addroommate.html')
    return render(request, 'main/addroommate.html')

def add_address(request):
    if request.method == "POST":
        name = request.POST['address-name']
        location = request.POST['address-location']
        description = request.POST['description']
        photo = request.FILES['picture__input']
        total_roommates = request.POST['total-roommates']
        address = Address(name=name, location=location, description=description, photo=photo, total_roommates=total_roommates)
        address.save()
        messages.success(request, 'Address added successfully')
        return render(request, 'main/addaddress.html')
    return render(request, 'main/addaddress.html')


def edit_profile(request):
    if request.method == "POST":
        name = request.POST.get('name', None)
        email = request.POST.get('email', None)
        phone = request.POST.get('phone', None)
        mobile = request.POST.get('mobile', None)
        address = request.POST.get('address', None)
        if name:
            request.user.first_name = " ".join(name.split(' ')[:-1])
            request.user.last_name = name.split(' ')[-1]
        if email:
            request.user.email = email
        if phone:
            request.user.userprofile.phone = phone
        if mobile:
            request.user.userprofile.mobile = mobile
        if address:
            request.user.userprofile.address = address
        request.user.save()
        request.user.userprofile.save()
        
        website = request.POST.get('website', None)
        github = request.POST.get('github', None)
        twitter = request.POST.get('twitter', None)
        instagram = request.POST.get('instagram', None)
        facebook = request.POST.get('facebook', None)
        if website:
            request.user.userprofile.socialmedia.website = website
        if github:
            request.user.userprofile.socialmedia.github = github
        if twitter:
            request.user.userprofile.socialmedia.twitter = twitter
        if instagram:
            request.user.userprofile.socialmedia.instagram = instagram
        if facebook:
            request.user.userprofile.socialmedia.facebook = facebook
        request.user.userprofile.socialmedia.save()
        messages.success(request, 'Profile updated successfully')
        return redirect('main:profile')

    return redirect("main:profile")


def address_view(request, pk):
    address = Address.objects.get(id=pk)
    # reviews = address.addressreview_set.all()
    return render(request, 'main/addressdetails.html', {'address': address})


def address_add_review(request, pk):
    address = Address.objects.get(id=pk)
    if request.method == "POST":
        address.addressreview_set.create(author=request.user, text=request.POST['review'], rating=request.POST['rate'])
        messages.success(request, 'Review added successfully')
        return render(request, 'main/addressdetails.html', {'address': address})
    return render(request, 'main/addressdetails.html', {'address': address})


def roommate_add_review(request, pk):
    roommate = UserProfile.objects.get(id=pk)
    if request.method == "POST":
        rev = roommate.roommatereview_set.create(author=request.user, text=request.POST['review'], rating=request.POST['rate'])
        rev.save()
        attributes = request.POST.get('attribute_list', None)
        if attributes:
            for i in json.loads(attributes):
                attr = roommate.attribute_set.get_or_create(name=i[0], rating=i[1],)[0]
                attr.review.add(rev)
                attr.save()
        messages.success(request, 'Review added successfully')
        print(request.POST['attribute_list'])
        return render(request, 'main/roommatedetails.html', {'userp': roommate})
    return render(request, 'main/roommatedetails.html', {'userp': roommate})

templates/main/addaddress.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/addroommate.css' %}">
{% endblock %}

{% block content %}
<div class="container">

    <h2 class="text-center my-3">Add Address</h2>

    <div class="p-4 border rounded shadow">
        <form action="{% url 'main:add_address' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <p class="mb-0 mb-1">Address Name:</p>
            <input type="text" class="form-control " placeholder="Enter Name" name="address-name">
            <label for="">Location:</label>
            <input type="text" class="form-control" name="address-location">
            <label for="">Description:</label>
            <textarea name="description" id="" cols="30" rows="10" class="form-control" name="description"></textarea>
            <label for="">Total roommates:</label>
            <input type="number" class="form-control mb-3" name="total-roommates">
            <label class="picture" for="picture__input" tabIndex="0">
                <span class="picture__image"></span>
            </label>

            <input type="file" name="picture__input" id="picture__input">
            <div class="text-end mt-5">
                <button class="btn btn-primary" type="submit">submit</button>
            </div>
        </form>
        

    </div>
    
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'js/addroommate.js' %}"></script>
{% endblock %}

templates/main/addressdetails.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/roommatedetails.css' %}">
<link rel="stylesheet" href="{% static 'css/rating.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="main-body mt-4">
        <div class='container'>
            <div class="row g-4 d-flex align-items-center">
                <div class="col-12 col-md-6">
                    <div>
                        <img src='{{address.photo.url}}' alt="" class="img-fluid" />
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <h4 class='mb-4'>{{address.name}}</h4>
                    <h6 class="text-secondary">Total roommate: {{address.total_roommates}} </h6>
                    <h6 class="text-secondary">Location: {{address.location}}</h6>
                    <h6 class="text-secondary">Avarage ratings: {% if address.average_rating == 0 %}Not Rated yet{% else %}{{address.average_rating}}{% endif %} </h6>
                    <p class='my-4'><span class='fw-bolder'>Description</span>: {{address.description}}</p>
                </div>
            </div>
        </div>
        <!-- add Reviews -->
        <div class="add-review mt-5">
            <h3>Add Review</h3>
            <form action="{% url 'main:address_add_review' address.id %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <h6>Rate</h6>
                    <div class="rating">
                        <label>
                          <input type="radio" name="rate" value="1" />
                          <span class="icon">★</span>
                        </label>
                        <label>
                          <input type="radio" name="rate" value="2" />
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                        </label>
                        <label>
                          <input type="radio" name="rate" value="3" />
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>   
                        </label>
                        <label>
                          <input type="radio" name="rate" value="4" />
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                        </label>
                        <label>
                          <input type="radio" name="rate" value="5" />
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                        </label>
                    </div>
                    <div class="form-group ">
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
                            name="review"></textarea>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <h3 class="mt-5">Reviews</h3>

        {% if address.addressreview_set.all %}
        {% for review in address.addressreview_set.all %}
        <div class="main-div">
            <div class="main-div-2">
                <h3 class="ovarall-review">{{review.rating}}</h3>
                <div class="child-div">
                    <a href="{% url 'main:profile_view' review.author.id %}">{{review.author.username}}</a>
                    <p>{{review.text}}</p>

                </div>
                <p><small>{{review.created_date|date:"SHORT_DATE_FORMAT"}}</small></p>
            </div>
            </div>
        {% endfor %}
        {% else %}
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h1 class="text-center">No Reviews Yet</h1>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}




    </div>
</div>

{% endblock %}

{% block script %}
<script>
    $(':radio').change(function() {
  console.log('New star rating: ' + this.value);
});
</script>
{% endblock %}

templates/main/addroommate.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/addroommate.css' %}">
<link rel="stylesheet" href="{% static 'css/rating.css' %}">

{% endblock %}

{% block content %}


<div class="container">

    <h2 class="text-center my-3">Add Roommate</h2>

    <div class="p-4 border rounded shadow">
        <form action="{% url 'main:add_roommate' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p class="mb-0 mb-1">Name:</p>
            <input type="text" class="form-control mb-3" placeholder="Enter Name" name="full-name">
            <p class="mb-0 mb-1">Email:</p>
            <input type="email" class="form-control mb-3" placeholder="Enter Email" name="email">
            <p class="mb-0 mb-1">Phone:</p>
            <input type="text" class="form-control mb-3" placeholder="Enter Phone" name="phone">
            <p class="mb-0 mb-1">Mobile:</p>
            <input type="text" class="form-control mb-3" placeholder="Enter Mobile" name="mobile">
            <p class="mb-0 mb-1">Address:</p>
            <input type="text" class="form-control mb-3" placeholder="Enter Address" name="address">
            <label class="picture" for="picture__input" tabIndex="0">
                <span class="picture__image"></span>
            </label>

            <input type="file" name="picture__input" id="picture__input">

            
            <ol id="list"></ol>
            <div class="row">
                <h4 class="mt-2">Attributes</h4>
                <input type="hidden" name="attribute_list" id="attrList">
                <div class="col-8">
                    <input type="text" name="" id="attr" list="attributes" class="form-control">
                </div>
                <datalist id="attributes">
                    {% for attribute in all_attributes %}
                    <option value="{{attribute.name}}"></option>

                    {% endfor %}
                </datalist>
                <div class="col-4 d-flex justify-content-around">
                    <div class="rating">
                        <label>
                          <input type="radio" name="stars" value="1" />
                          <span class="icon">★</span>
                        </label>
                        <label>
                          <input type="radio" name="stars" value="2" />
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                        </label>
                        <label>
                          <input type="radio" name="stars" value="3" />
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>   
                        </label>
                        <label>
                          <input type="radio" name="stars" value="4" />
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                        </label>
                        <label>
                          <input type="radio" name="stars" value="5" />
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                          <span class="icon">★</span>
                        </label>
                    </div>
                   
                    <button class="btn btn-primary" type="button" onclick="add_attribute()">Add</button>
                </div>
            </div>


            <div class="text-end mt-5">
                <button class="btn btn-primary">submit</button>
            </div>
        </form>
    </div>

</div>



{% endblock %}
{% block scripts %}
<script src="{% static 'js/addroommate.js' %}"></script>
<script>
    $(':radio').change(function() {
  console.log('New star rating: ' + this.value);
});
</script>
{% endblock %}

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="wrapper">
    <section class="hero">

        <div class="sec1">
            <div class="container">
                <h1 id="head-text" class="text-center header-main text-white position-relative z-5 fw-bold">Welcome to
                    Roommate
                    Finder</h1>

                <form action="{% url 'main:search' %}" method="get">
                    <input type="text" class="header-input" name="Roommate" id="header-input"
                        placeholder="Enter Roommate name..">
                </form>
                <h4 class="text-center text-white or ">or</h4>
                <h1 onclick="cngHeadText()" id="head-text2"
                    class="text-center header-main2 text-white position-relative z-5 ">Find your perfect Address
                    today!</h1>
            </div>
            <div class="header-black">

            </div>
        </div>
    </section>

    <div class="container my-5 w-100">
        <div class="row g-5">
            <div class="col-12 col-md-4">
                <div class="text-center w-100">
                    <img style="height: 200px;" class="w-50 text-center" src="{% static 'gallery/rating.png' %}" alt="">
                    <h3 class="mt-3">Manage and edit your ratings</h3>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="text-center w-100">
                    <img style="height: 200px;" class="w-50 text-center" src="{% static 'gallery/book (1).png' %}" alt="">
                    <h3 class="mt-3">Your ratings are always anonymous</h3>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="text-center w-100">
                    <img style="height: 200px;" class="w-50 text-center" src="{% static 'gallery/positive-vote.png' %}" alt="">
                    <h3 class="mt-3">Like or dislike ratings</h3>
                </div>
            </div>
        </div>

    </div>

</div>


    {% endblock%}

templates/main/search.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/search.css' %}">
<link rel="stylesheet" href="{% static 'css/addressdetails.css' %}">
{% endblock %}

{% block content %}

<h4 class="text-center mt-4"><b>{{total}}</b> {{key}} with <b>"{{keyword}}"</b> in their name</h4>



<div class="container" style="min-height: 600px;">
    {% if roommate_list %}
    {% for roommate in roommate_list %}
    <a href="{% url 'main:profile_view' roommate.id %}" class="text-decoration-none"> 
        <div class="search-main-div2">
            <i class="fa-solid fa-arrow-right"></i>

            <div class="search-main-div">
                <div class="div1">
                    <h2 class="p-4 div1-text fw-bold text-center">4.3</h2>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-regular fa-star"></i>
                </div>
                <div class="div2">
                    <h3 class="mb-4 ms-3">{{roommate.full_name}}</h3>
                    <div class="div2-maindiv">
                        <p class="fw-bold mb-0">smoke</p>
                        <div class="emtydiv">
                            <p class=" mb-0 w-50 h-100 bg-warning"></p>
                        </div>
                        <p class="fw-bold mb-0">50%</p>
                    </div>


                    <div class="div2-maindiv">
                        <p class="fw-bold mb-0">noise</p>
                        <div class="emtydiv">
                            <p class=" mb-0 w-100 h-100 bg-success"></p>
                        </div>
                        <p class="fw-bold mb-0">98%</p>
                    </div>

                </div>
            </div>
        </div>
    </a>
    {% endfor %}
    {% else %}
    <div class="text-center mt-5">
        <h1 class="text-center">No {{key}} Found</h1>
    </div>
    {% endif %}



</div>


{% endblock%}

templates/main/searchaddress.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/search.css' %}">
<link rel="stylesheet" href="{% static 'css/addressdetails.css' %}">
{% endblock %}

{% block content %}

<h4 class="text-center mt-4"><b>{{total}}</b> {{key}} with <b>"{{keyword}}"</b> in their name</h4>



<div class="container" style="min-height: 600px;">
    {% if address_list %}
    {% for address in address_list %}
    <a href="{% url 'main:address_view' address.id %}" class="text-decoration-none">
        <div class="search-main-div2">
            <i class="fa-solid fa-arrow-right"></i>

            <div class="search-main-div">
                <div class="div1">
                    <h2 class="p-4 div1-text fw-bold text-center">4.3</h2>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-regular fa-star"></i>
                </div>
                <div class="div2">
                    <h3 class="mb-4 ms-3">{{address.name}}</h3>
                    <div class="div2-maindiv">
                        <p class="fw-bold mb-0">smoke</p>
                        <div class="emtydiv">
                            <p class=" mb-0 w-50 h-100 bg-warning"></p>
                        </div>
                        <p class="fw-bold mb-0">50%</p>
                    </div>


                    <div class="div2-maindiv">
                        <p class="fw-bold mb-0">noise</p>
                        <div class="emtydiv">
                            <p class=" mb-0 w-100 h-100 bg-success"></p>
                        </div>
                        <p class="fw-bold mb-0">98%</p>
                    </div>

                </div>
            </div>
        </div>
    </a>
    {% endfor %}
    {% else %}
    <div class="text-center mt-5">
        <h1 class="text-center">No {{key}} Found</h1>
    </div>
    {% endif %}






</div>

{% endblock %}






<footer class="footer-distributed">

    <div class="footer-left">

        <h3>Company<span>logo</span></h3>

        <p class="footer-links">
            <a href="#" class="link-1">Home</a>

            <a href="#">Blog</a>

            <a href="#">Pricing</a>

            <a href="#">About</a>

            <a href="#">Faq</a>

            <a href="#">Contact</a>
        </p>

        <p class="footer-company-name">Company Name © 2015</p>
    </div>

    <div class="footer-center">

        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>444 S. Cedros Ave</span> Solana Beach, California</p>
        </div>

        <div>
            <i class="fa fa-phone"></i>
            <p>+1.555.555.5555</p>
        </div>

        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:support@company.com">support@company.com</a></p>
        </div>

    </div>

    <div class="footer-right">

        <p class="footer-company-about">
            <span>About the company</span>
            Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor
            lacus vehicula sit amet.
        </p>

        <!-- <div class="footer-icons">

                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-github"></i></a>

            </div> -->

    </div>

</footer>


<script src="index.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>

</body>

</html>