accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:id>', views.profile_view, name="profile_view"),
    path('search/', views.search, name='search'),
    path('addroommate/', views.add_roommate, name='add_roommate'),
    path('addaddress/', views.add_address, name='add_address'),
    path('address/<int:pk>', views.address_view, name='address_view'),
    path('address-add-review/<int:pk>', views.address_add_review, name='address_add_review'),
    path('edit-profile', views.edit_profile, name="edit-profile"),
    path('roommate-add-review/<int:pk>', views.roommate_add_review, name='roommate_add_review'),
] 

ratemyroomie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf  import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rate my Rommie</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {% block style %}{% endblock %}


</head>

<body>
    {% if user.is_authenticated %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endif %}
    <div class="nav-con">
        <div class="nav-con2">
            <a href="{% url 'main:home' %}" class="text-decoration-none text-white">
                <h3>LoGo</h3>
            </a>
            <div class=" search-con">
                <div class="dropdown">
                    <button id="nav-btn" class="btn  dropdown-toggle border text-white" type="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Roommate
                    </button>
                    <ul class="dropdown-menu">
                        <li onclick="cngNavElemets('Address')"><a class="dropdown-item" href="#">Address</a></li>
                        <li onclick="cngNavElemets('Roommate')"><a class="dropdown-item" href="#">Roommate</a></li>
                    </ul>
                </div>
                <form action="{% url 'main:search' %}" method="get">
                    <input type="text" placeholder="enter Roommate" name="Roommate" class="nav-input" id="nav-input">
                </form>
            </div>
            <div class="navber_link">
                {% if user.is_authenticated %}
                <nav class="navbar navbar-expand-xxl navbar-light">
                    <button class="navbar-toggler bg-light ml-auto" type="button" data-toggle="collapse"
                        data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarMenu">
                        <ul class="navbar-nav ml-auto mt-1">
                            <!-- Menu items -->
                            <li class="nav-item">
                                <a class="nav-link text-white text-right px-2" href="{% url 'main:add_roommate' %}">Add Roommate</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white text-right px-2" href="{% url 'main:add_address' %}">Add Address</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white text-right px-2" href="{% url 'main:profile' %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white text-right px-2" href="{% url 'accounts:logout' %}">Logout</a>
                            </li>
                        </ul>
                    </div>
                </nav>
                {% else %}
                <a class="btn btn-primary" href="{% url 'accounts:login' %}">Login</a>
                <a class="btn btn-danger" href="{% url 'accounts:register' %}">Sign Up</a>
                {% endif %}


            </div>
        </div>
    </div>

    {% block content %}{% endblock %}
    <footer class="footer-distributed">

        <div class="footer-left">

            <h3>Company<span>logo</span></h3>

            <p class="footer-links">
                <a href="#" class="link-1">Home</a>

                <a href="#">Blog</a>

                <a href="#">Pricing</a>

                <a href="#">About</a>

                <a href="#">Faq</a>

                <a href="#">Contact</a>
            </p>

            <p class="footer-company-name">Company Name © 2015</p>
        </div>

        <div class="footer-center">

            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>444 S. Cedros Ave</span> Solana Beach, California</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+1.555.555.5555</p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:support@company.com">support@company.com</a></p>
            </div>

        </div>

        <div class="footer-right">

            <p class="footer-company-about">
                <span>About the company</span>
                Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor
                lacus vehicula sit amet.
            </p>



        </div>

    </footer>


    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


    <script src="{% static 'js/index.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>


    {% block scripts %}{% endblock %}
</body>

</html>